### ISSUE TITLE
Read tcp files with -n option

### ISSUE THREAD

**Issue by rockwotj** [rieck/derrick#2]
If I record traffic with tcpdump with the `-n` flag specified (see [manpage][1]) then derrick outputs nothing, but if I remove that flag then derrick can read the generated pcap files. Is there anyway to read those files with `-n` option of tcpdump enabled? I want to include it for performance reasons.

[1]: http://www.tcpdump.org/tcpdump_man.html

**Comment by rieck** [comment]
This sounds strange. Can you provide an example? 

The `-n` flag of  tcpdump only controls the output of the tool not the data written to file via `-w`. I am surprised to hear that there is an impact on derrick.

**Comment by rockwotj** [comment]
nevermind, sorry it was another issue. Thanks for the great tool!
